#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnote.H5P.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Dnote.H5P")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertH5P_Content(H5P_Content instance);
    partial void UpdateH5P_Content(H5P_Content instance);
    partial void DeleteH5P_Content(H5P_Content instance);
    partial void InsertH5P_Content_Dependency(H5P_Content_Dependency instance);
    partial void UpdateH5P_Content_Dependency(H5P_Content_Dependency instance);
    partial void DeleteH5P_Content_Dependency(H5P_Content_Dependency instance);
    partial void InsertH5P_Library(H5P_Library instance);
    partial void UpdateH5P_Library(H5P_Library instance);
    partial void DeleteH5P_Library(H5P_Library instance);
    partial void InsertH5P_Library_Dependency(H5P_Library_Dependency instance);
    partial void UpdateH5P_Library_Dependency(H5P_Library_Dependency instance);
    partial void DeleteH5P_Library_Dependency(H5P_Library_Dependency instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Dnote.H5P.Linq.Properties.Settings.Default.Dnote_H5PConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<H5P_Content> H5P_Contents
		{
			get
			{
				return this.GetTable<H5P_Content>();
			}
		}
		
		public System.Data.Linq.Table<H5P_Content_Dependency> H5P_Content_Dependencies
		{
			get
			{
				return this.GetTable<H5P_Content_Dependency>();
			}
		}
		
		public System.Data.Linq.Table<H5P_Library> H5P_Libraries
		{
			get
			{
				return this.GetTable<H5P_Library>();
			}
		}
		
		public System.Data.Linq.Table<H5P_Library_Dependency> H5P_Library_Dependencies
		{
			get
			{
				return this.GetTable<H5P_Library_Dependency>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[H5P.Content]")]
	public partial class H5P_Content : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Title;
		
		private string _Language;
		
		private int _MainLibraryId;
		
		private string _License;
		
		private string _DefaultLanguage;
		
		private EntitySet<H5P_Content_Dependency> _H5P_Content_Dependencies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnMainLibraryIdChanging(int value);
    partial void OnMainLibraryIdChanged();
    partial void OnLicenseChanging(string value);
    partial void OnLicenseChanged();
    partial void OnDefaultLanguageChanging(string value);
    partial void OnDefaultLanguageChanged();
    #endregion
		
		public H5P_Content()
		{
			this._H5P_Content_Dependencies = new EntitySet<H5P_Content_Dependency>(new Action<H5P_Content_Dependency>(this.attach_H5P_Content_Dependencies), new Action<H5P_Content_Dependency>(this.detach_H5P_Content_Dependencies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainLibraryId", DbType="Int NOT NULL")]
		public int MainLibraryId
		{
			get
			{
				return this._MainLibraryId;
			}
			set
			{
				if ((this._MainLibraryId != value))
				{
					this.OnMainLibraryIdChanging(value);
					this.SendPropertyChanging();
					this._MainLibraryId = value;
					this.SendPropertyChanged("MainLibraryId");
					this.OnMainLibraryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_License", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string License
		{
			get
			{
				return this._License;
			}
			set
			{
				if ((this._License != value))
				{
					this.OnLicenseChanging(value);
					this.SendPropertyChanging();
					this._License = value;
					this.SendPropertyChanged("License");
					this.OnLicenseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultLanguage", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string DefaultLanguage
		{
			get
			{
				return this._DefaultLanguage;
			}
			set
			{
				if ((this._DefaultLanguage != value))
				{
					this.OnDefaultLanguageChanging(value);
					this.SendPropertyChanging();
					this._DefaultLanguage = value;
					this.SendPropertyChanged("DefaultLanguage");
					this.OnDefaultLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Content_H5P_Content_Dependency", Storage="_H5P_Content_Dependencies", ThisKey="Id", OtherKey="ContentId")]
		public EntitySet<H5P_Content_Dependency> H5P_Content_Dependencies
		{
			get
			{
				return this._H5P_Content_Dependencies;
			}
			set
			{
				this._H5P_Content_Dependencies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_H5P_Content_Dependencies(H5P_Content_Dependency entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Content = this;
		}
		
		private void detach_H5P_Content_Dependencies(H5P_Content_Dependency entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Content = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[H5P.Content.Dependencies]")]
	public partial class H5P_Content_Dependency : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ContentId;
		
		private int _LibraryId;
		
		private EntityRef<H5P_Content> _H5P_Content;
		
		private EntityRef<H5P_Library> _H5P_Library;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnContentIdChanging(int value);
    partial void OnContentIdChanged();
    partial void OnLibraryIdChanging(int value);
    partial void OnLibraryIdChanged();
    #endregion
		
		public H5P_Content_Dependency()
		{
			this._H5P_Content = default(EntityRef<H5P_Content>);
			this._H5P_Library = default(EntityRef<H5P_Library>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentId", DbType="Int NOT NULL")]
		public int ContentId
		{
			get
			{
				return this._ContentId;
			}
			set
			{
				if ((this._ContentId != value))
				{
					if (this._H5P_Content.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnContentIdChanging(value);
					this.SendPropertyChanging();
					this._ContentId = value;
					this.SendPropertyChanged("ContentId");
					this.OnContentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibraryId", DbType="Int NOT NULL")]
		public int LibraryId
		{
			get
			{
				return this._LibraryId;
			}
			set
			{
				if ((this._LibraryId != value))
				{
					if (this._H5P_Library.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLibraryIdChanging(value);
					this.SendPropertyChanging();
					this._LibraryId = value;
					this.SendPropertyChanged("LibraryId");
					this.OnLibraryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Content_H5P_Content_Dependency", Storage="_H5P_Content", ThisKey="ContentId", OtherKey="Id", IsForeignKey=true)]
		public H5P_Content H5P_Content
		{
			get
			{
				return this._H5P_Content.Entity;
			}
			set
			{
				H5P_Content previousValue = this._H5P_Content.Entity;
				if (((previousValue != value) 
							|| (this._H5P_Content.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._H5P_Content.Entity = null;
						previousValue.H5P_Content_Dependencies.Remove(this);
					}
					this._H5P_Content.Entity = value;
					if ((value != null))
					{
						value.H5P_Content_Dependencies.Add(this);
						this._ContentId = value.Id;
					}
					else
					{
						this._ContentId = default(int);
					}
					this.SendPropertyChanged("H5P_Content");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_Content_Dependency", Storage="_H5P_Library", ThisKey="LibraryId", OtherKey="Id", IsForeignKey=true)]
		public H5P_Library H5P_Library
		{
			get
			{
				return this._H5P_Library.Entity;
			}
			set
			{
				H5P_Library previousValue = this._H5P_Library.Entity;
				if (((previousValue != value) 
							|| (this._H5P_Library.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._H5P_Library.Entity = null;
						previousValue.H5P_Content_Dependencies.Remove(this);
					}
					this._H5P_Library.Entity = value;
					if ((value != null))
					{
						value.H5P_Content_Dependencies.Add(this);
						this._LibraryId = value.Id;
					}
					else
					{
						this._LibraryId = default(int);
					}
					this.SendPropertyChanged("H5P_Library");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[H5P.Library]")]
	public partial class H5P_Library : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Title;
		
		private int _MajorVersion;
		
		private int _MinorVersion;
		
		private int _PatchVersion;
		
		private int _Runnable;
		
		private string _Author;
		
		private string _License;
		
		private string _MachineName;
		
		private EntitySet<H5P_Content_Dependency> _H5P_Content_Dependencies;
		
		private EntitySet<H5P_Library_Dependency> _H5P_Library_Dependencies;
		
		private EntitySet<H5P_Library_Dependency> _H5P_Library_Dependencies1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnMajorVersionChanging(int value);
    partial void OnMajorVersionChanged();
    partial void OnMinorVersionChanging(int value);
    partial void OnMinorVersionChanged();
    partial void OnPatchVersionChanging(int value);
    partial void OnPatchVersionChanged();
    partial void OnRunnableChanging(int value);
    partial void OnRunnableChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnLicenseChanging(string value);
    partial void OnLicenseChanged();
    partial void OnMachineNameChanging(string value);
    partial void OnMachineNameChanged();
    #endregion
		
		public H5P_Library()
		{
			this._H5P_Content_Dependencies = new EntitySet<H5P_Content_Dependency>(new Action<H5P_Content_Dependency>(this.attach_H5P_Content_Dependencies), new Action<H5P_Content_Dependency>(this.detach_H5P_Content_Dependencies));
			this._H5P_Library_Dependencies = new EntitySet<H5P_Library_Dependency>(new Action<H5P_Library_Dependency>(this.attach_H5P_Library_Dependencies), new Action<H5P_Library_Dependency>(this.detach_H5P_Library_Dependencies));
			this._H5P_Library_Dependencies1 = new EntitySet<H5P_Library_Dependency>(new Action<H5P_Library_Dependency>(this.attach_H5P_Library_Dependencies1), new Action<H5P_Library_Dependency>(this.detach_H5P_Library_Dependencies1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MajorVersion", DbType="Int NOT NULL")]
		public int MajorVersion
		{
			get
			{
				return this._MajorVersion;
			}
			set
			{
				if ((this._MajorVersion != value))
				{
					this.OnMajorVersionChanging(value);
					this.SendPropertyChanging();
					this._MajorVersion = value;
					this.SendPropertyChanged("MajorVersion");
					this.OnMajorVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinorVersion", DbType="Int NOT NULL")]
		public int MinorVersion
		{
			get
			{
				return this._MinorVersion;
			}
			set
			{
				if ((this._MinorVersion != value))
				{
					this.OnMinorVersionChanging(value);
					this.SendPropertyChanging();
					this._MinorVersion = value;
					this.SendPropertyChanged("MinorVersion");
					this.OnMinorVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatchVersion", DbType="Int NOT NULL")]
		public int PatchVersion
		{
			get
			{
				return this._PatchVersion;
			}
			set
			{
				if ((this._PatchVersion != value))
				{
					this.OnPatchVersionChanging(value);
					this.SendPropertyChanging();
					this._PatchVersion = value;
					this.SendPropertyChanged("PatchVersion");
					this.OnPatchVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Runnable", DbType="Int NOT NULL")]
		public int Runnable
		{
			get
			{
				return this._Runnable;
			}
			set
			{
				if ((this._Runnable != value))
				{
					this.OnRunnableChanging(value);
					this.SendPropertyChanging();
					this._Runnable = value;
					this.SendPropertyChanged("Runnable");
					this.OnRunnableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_License", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string License
		{
			get
			{
				return this._License;
			}
			set
			{
				if ((this._License != value))
				{
					this.OnLicenseChanging(value);
					this.SendPropertyChanging();
					this._License = value;
					this.SendPropertyChanged("License");
					this.OnLicenseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this.OnMachineNameChanging(value);
					this.SendPropertyChanging();
					this._MachineName = value;
					this.SendPropertyChanged("MachineName");
					this.OnMachineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_Content_Dependency", Storage="_H5P_Content_Dependencies", ThisKey="Id", OtherKey="LibraryId")]
		public EntitySet<H5P_Content_Dependency> H5P_Content_Dependencies
		{
			get
			{
				return this._H5P_Content_Dependencies;
			}
			set
			{
				this._H5P_Content_Dependencies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_Library_Dependency", Storage="_H5P_Library_Dependencies", ThisKey="Id", OtherKey="LibraryId")]
		public EntitySet<H5P_Library_Dependency> H5P_Library_Dependencies
		{
			get
			{
				return this._H5P_Library_Dependencies;
			}
			set
			{
				this._H5P_Library_Dependencies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_Library_Dependency1", Storage="_H5P_Library_Dependencies1", ThisKey="Id", OtherKey="ReferencedLibraryId")]
		public EntitySet<H5P_Library_Dependency> H5P_Library_Dependencies1
		{
			get
			{
				return this._H5P_Library_Dependencies1;
			}
			set
			{
				this._H5P_Library_Dependencies1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_H5P_Content_Dependencies(H5P_Content_Dependency entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library = this;
		}
		
		private void detach_H5P_Content_Dependencies(H5P_Content_Dependency entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library = null;
		}
		
		private void attach_H5P_Library_Dependencies(H5P_Library_Dependency entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library = this;
		}
		
		private void detach_H5P_Library_Dependencies(H5P_Library_Dependency entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library = null;
		}
		
		private void attach_H5P_Library_Dependencies1(H5P_Library_Dependency entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library1 = this;
		}
		
		private void detach_H5P_Library_Dependencies1(H5P_Library_Dependency entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[H5P.Library.Dependencies]")]
	public partial class H5P_Library_Dependency : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _LibraryId;
		
		private int _ReferencedLibraryId;
		
		private EntityRef<H5P_Library> _H5P_Library;
		
		private EntityRef<H5P_Library> _H5P_Library1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLibraryIdChanging(int value);
    partial void OnLibraryIdChanged();
    partial void OnReferencedLibraryIdChanging(int value);
    partial void OnReferencedLibraryIdChanged();
    #endregion
		
		public H5P_Library_Dependency()
		{
			this._H5P_Library = default(EntityRef<H5P_Library>);
			this._H5P_Library1 = default(EntityRef<H5P_Library>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibraryId", DbType="Int NOT NULL")]
		public int LibraryId
		{
			get
			{
				return this._LibraryId;
			}
			set
			{
				if ((this._LibraryId != value))
				{
					if (this._H5P_Library.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLibraryIdChanging(value);
					this.SendPropertyChanging();
					this._LibraryId = value;
					this.SendPropertyChanged("LibraryId");
					this.OnLibraryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferencedLibraryId", DbType="Int NOT NULL")]
		public int ReferencedLibraryId
		{
			get
			{
				return this._ReferencedLibraryId;
			}
			set
			{
				if ((this._ReferencedLibraryId != value))
				{
					if (this._H5P_Library1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReferencedLibraryIdChanging(value);
					this.SendPropertyChanging();
					this._ReferencedLibraryId = value;
					this.SendPropertyChanged("ReferencedLibraryId");
					this.OnReferencedLibraryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_Library_Dependency", Storage="_H5P_Library", ThisKey="LibraryId", OtherKey="Id", IsForeignKey=true)]
		public H5P_Library H5P_Library
		{
			get
			{
				return this._H5P_Library.Entity;
			}
			set
			{
				H5P_Library previousValue = this._H5P_Library.Entity;
				if (((previousValue != value) 
							|| (this._H5P_Library.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._H5P_Library.Entity = null;
						previousValue.H5P_Library_Dependencies.Remove(this);
					}
					this._H5P_Library.Entity = value;
					if ((value != null))
					{
						value.H5P_Library_Dependencies.Add(this);
						this._LibraryId = value.Id;
					}
					else
					{
						this._LibraryId = default(int);
					}
					this.SendPropertyChanged("H5P_Library");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_Library_Dependency1", Storage="_H5P_Library1", ThisKey="ReferencedLibraryId", OtherKey="Id", IsForeignKey=true)]
		public H5P_Library H5P_Library1
		{
			get
			{
				return this._H5P_Library1.Entity;
			}
			set
			{
				H5P_Library previousValue = this._H5P_Library1.Entity;
				if (((previousValue != value) 
							|| (this._H5P_Library1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._H5P_Library1.Entity = null;
						previousValue.H5P_Library_Dependencies1.Remove(this);
					}
					this._H5P_Library1.Entity = value;
					if ((value != null))
					{
						value.H5P_Library_Dependencies1.Add(this);
						this._ReferencedLibraryId = value.Id;
					}
					else
					{
						this._ReferencedLibraryId = default(int);
					}
					this.SendPropertyChanged("H5P_Library1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
