<?xml version="1.0" encoding="utf-8"?><Database Name="Dnote.H5P" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Dnote.H5P;Integrated Security=True" SettingsObjectName="Dnote.H5P.NetFW.Linq2Sql.Properties.Settings" SettingsPropertyName="Dnote_H5PConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[H5P.ContentItems]" Member="H5P_ContentItems">
    <Type Name="H5P_ContentItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContentId" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MainLibraryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="License" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultLanguage" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="H5P_ContentItem_H5P_ContentItem_Library" Member="H5P_ContentItem_Libraries" ThisKey="Id" OtherKey="ContentItemId" Type="H5P_ContentItem_Library" />
      <Association Name="H5P_ContentItem_H5P_ContentItem_EmbedType" Member="H5P_ContentItem_EmbedTypes" ThisKey="Id" OtherKey="ContentId" Type="H5P_ContentItem_EmbedType" />
    </Type>
  </Table>
  <Table Name="dbo.[H5P.ContentItem.Libraries]" Member="H5P_ContentItem_Libraries">
    <Type Name="H5P_ContentItem_Library">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContentItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LibraryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="H5P_ContentItem_H5P_ContentItem_Library" Member="H5P_ContentItem" ThisKey="ContentItemId" OtherKey="Id" Type="H5P_ContentItem" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="H5P_Library_H5P_ContentItem_Library" Member="H5P_Library" ThisKey="LibraryId" OtherKey="Id" Type="H5P_Library" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[H5P.ContentItem.EmbedTypes]" Member="H5P_ContentItem_EmbedTypes">
    <Type Name="H5P_ContentItem_EmbedType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="H5P_ContentItem_H5P_ContentItem_EmbedType" Member="H5P_ContentItem" ThisKey="ContentId" OtherKey="Id" Type="H5P_ContentItem" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[H5P.Libraries]" Member="H5P_Libraries">
    <Type Name="H5P_Library">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MajorVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinorVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatchVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CoreApiMajorVersion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoreApiMinorVersion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AddedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="H5P_Library_H5P_ContentItem_Library" Member="H5P_ContentItem_Libraries" ThisKey="Id" OtherKey="LibraryId" Type="H5P_ContentItem_Library" />
      <Association Name="H5P_Library_H5P_Library_File" Member="H5P_Library_Files" ThisKey="Id" OtherKey="LibraryId" Type="H5P_Library_File" />
    </Type>
  </Table>
  <Table Name="dbo.[H5P.Library.Files]" Member="H5P_Library_Files">
    <Type Name="H5P_Library_File">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LibraryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="H5P_Library_H5P_Library_File" Member="H5P_Library" ThisKey="LibraryId" OtherKey="Id" Type="H5P_Library" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>