#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnote.H5P.NetFW.Linq2Sql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Dnote.H5P")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertH5P_ContentItem(H5P_ContentItem instance);
    partial void UpdateH5P_ContentItem(H5P_ContentItem instance);
    partial void DeleteH5P_ContentItem(H5P_ContentItem instance);
    partial void InsertH5P_ContentItem_Library(H5P_ContentItem_Library instance);
    partial void UpdateH5P_ContentItem_Library(H5P_ContentItem_Library instance);
    partial void DeleteH5P_ContentItem_Library(H5P_ContentItem_Library instance);
    partial void InsertH5P_ContentItem_EmbedType(H5P_ContentItem_EmbedType instance);
    partial void UpdateH5P_ContentItem_EmbedType(H5P_ContentItem_EmbedType instance);
    partial void DeleteH5P_ContentItem_EmbedType(H5P_ContentItem_EmbedType instance);
    partial void InsertH5P_Library(H5P_Library instance);
    partial void UpdateH5P_Library(H5P_Library instance);
    partial void DeleteH5P_Library(H5P_Library instance);
    partial void InsertH5P_Library_File(H5P_Library_File instance);
    partial void UpdateH5P_Library_File(H5P_Library_File instance);
    partial void DeleteH5P_Library_File(H5P_Library_File instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Dnote.H5P.NetFW.Linq2Sql.Properties.Settings.Default.Dnote_H5PConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<H5P_ContentItem> H5P_ContentItems
		{
			get
			{
				return this.GetTable<H5P_ContentItem>();
			}
		}
		
		public System.Data.Linq.Table<H5P_ContentItem_Library> H5P_ContentItem_Libraries
		{
			get
			{
				return this.GetTable<H5P_ContentItem_Library>();
			}
		}
		
		public System.Data.Linq.Table<H5P_ContentItem_EmbedType> H5P_ContentItem_EmbedTypes
		{
			get
			{
				return this.GetTable<H5P_ContentItem_EmbedType>();
			}
		}
		
		public System.Data.Linq.Table<H5P_Library> H5P_Libraries
		{
			get
			{
				return this.GetTable<H5P_Library>();
			}
		}
		
		public System.Data.Linq.Table<H5P_Library_File> H5P_Library_Files
		{
			get
			{
				return this.GetTable<H5P_Library_File>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[H5P.ContentItems]")]
	public partial class H5P_ContentItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ContentId;
		
		private string _Title;
		
		private string _Language;
		
		private int _MainLibraryId;
		
		private string _License;
		
		private string _DefaultLanguage;
		
		private EntitySet<H5P_ContentItem_Library> _H5P_ContentItem_Libraries;
		
		private EntitySet<H5P_ContentItem_EmbedType> _H5P_ContentItem_EmbedTypes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnContentIdChanging(string value);
    partial void OnContentIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnMainLibraryIdChanging(int value);
    partial void OnMainLibraryIdChanged();
    partial void OnLicenseChanging(string value);
    partial void OnLicenseChanged();
    partial void OnDefaultLanguageChanging(string value);
    partial void OnDefaultLanguageChanged();
    #endregion
		
		public H5P_ContentItem()
		{
			this._H5P_ContentItem_Libraries = new EntitySet<H5P_ContentItem_Library>(new Action<H5P_ContentItem_Library>(this.attach_H5P_ContentItem_Libraries), new Action<H5P_ContentItem_Library>(this.detach_H5P_ContentItem_Libraries));
			this._H5P_ContentItem_EmbedTypes = new EntitySet<H5P_ContentItem_EmbedType>(new Action<H5P_ContentItem_EmbedType>(this.attach_H5P_ContentItem_EmbedTypes), new Action<H5P_ContentItem_EmbedType>(this.detach_H5P_ContentItem_EmbedTypes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentId", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ContentId
		{
			get
			{
				return this._ContentId;
			}
			set
			{
				if ((this._ContentId != value))
				{
					this.OnContentIdChanging(value);
					this.SendPropertyChanging();
					this._ContentId = value;
					this.SendPropertyChanged("ContentId");
					this.OnContentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainLibraryId", DbType="Int NOT NULL")]
		public int MainLibraryId
		{
			get
			{
				return this._MainLibraryId;
			}
			set
			{
				if ((this._MainLibraryId != value))
				{
					this.OnMainLibraryIdChanging(value);
					this.SendPropertyChanging();
					this._MainLibraryId = value;
					this.SendPropertyChanged("MainLibraryId");
					this.OnMainLibraryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_License", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string License
		{
			get
			{
				return this._License;
			}
			set
			{
				if ((this._License != value))
				{
					this.OnLicenseChanging(value);
					this.SendPropertyChanging();
					this._License = value;
					this.SendPropertyChanged("License");
					this.OnLicenseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultLanguage", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string DefaultLanguage
		{
			get
			{
				return this._DefaultLanguage;
			}
			set
			{
				if ((this._DefaultLanguage != value))
				{
					this.OnDefaultLanguageChanging(value);
					this.SendPropertyChanging();
					this._DefaultLanguage = value;
					this.SendPropertyChanged("DefaultLanguage");
					this.OnDefaultLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_ContentItem_H5P_ContentItem_Library", Storage="_H5P_ContentItem_Libraries", ThisKey="Id", OtherKey="ContentItemId")]
		public EntitySet<H5P_ContentItem_Library> H5P_ContentItem_Libraries
		{
			get
			{
				return this._H5P_ContentItem_Libraries;
			}
			set
			{
				this._H5P_ContentItem_Libraries.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_ContentItem_H5P_ContentItem_EmbedType", Storage="_H5P_ContentItem_EmbedTypes", ThisKey="Id", OtherKey="ContentId")]
		public EntitySet<H5P_ContentItem_EmbedType> H5P_ContentItem_EmbedTypes
		{
			get
			{
				return this._H5P_ContentItem_EmbedTypes;
			}
			set
			{
				this._H5P_ContentItem_EmbedTypes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_H5P_ContentItem_Libraries(H5P_ContentItem_Library entity)
		{
			this.SendPropertyChanging();
			entity.H5P_ContentItem = this;
		}
		
		private void detach_H5P_ContentItem_Libraries(H5P_ContentItem_Library entity)
		{
			this.SendPropertyChanging();
			entity.H5P_ContentItem = null;
		}
		
		private void attach_H5P_ContentItem_EmbedTypes(H5P_ContentItem_EmbedType entity)
		{
			this.SendPropertyChanging();
			entity.H5P_ContentItem = this;
		}
		
		private void detach_H5P_ContentItem_EmbedTypes(H5P_ContentItem_EmbedType entity)
		{
			this.SendPropertyChanging();
			entity.H5P_ContentItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[H5P.ContentItem.Libraries]")]
	public partial class H5P_ContentItem_Library : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ContentItemId;
		
		private int _LibraryId;
		
		private int _Order;
		
		private EntityRef<H5P_ContentItem> _H5P_ContentItem;
		
		private EntityRef<H5P_Library> _H5P_Library;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnContentItemIdChanging(int value);
    partial void OnContentItemIdChanged();
    partial void OnLibraryIdChanging(int value);
    partial void OnLibraryIdChanged();
    partial void OnOrderChanging(int value);
    partial void OnOrderChanged();
    #endregion
		
		public H5P_ContentItem_Library()
		{
			this._H5P_ContentItem = default(EntityRef<H5P_ContentItem>);
			this._H5P_Library = default(EntityRef<H5P_Library>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentItemId", DbType="Int NOT NULL")]
		public int ContentItemId
		{
			get
			{
				return this._ContentItemId;
			}
			set
			{
				if ((this._ContentItemId != value))
				{
					if (this._H5P_ContentItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnContentItemIdChanging(value);
					this.SendPropertyChanging();
					this._ContentItemId = value;
					this.SendPropertyChanged("ContentItemId");
					this.OnContentItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibraryId", DbType="Int NOT NULL")]
		public int LibraryId
		{
			get
			{
				return this._LibraryId;
			}
			set
			{
				if ((this._LibraryId != value))
				{
					if (this._H5P_Library.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLibraryIdChanging(value);
					this.SendPropertyChanging();
					this._LibraryId = value;
					this.SendPropertyChanged("LibraryId");
					this.OnLibraryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int NOT NULL")]
		public int Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this.OnOrderChanging(value);
					this.SendPropertyChanging();
					this._Order = value;
					this.SendPropertyChanged("Order");
					this.OnOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_ContentItem_H5P_ContentItem_Library", Storage="_H5P_ContentItem", ThisKey="ContentItemId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public H5P_ContentItem H5P_ContentItem
		{
			get
			{
				return this._H5P_ContentItem.Entity;
			}
			set
			{
				H5P_ContentItem previousValue = this._H5P_ContentItem.Entity;
				if (((previousValue != value) 
							|| (this._H5P_ContentItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._H5P_ContentItem.Entity = null;
						previousValue.H5P_ContentItem_Libraries.Remove(this);
					}
					this._H5P_ContentItem.Entity = value;
					if ((value != null))
					{
						value.H5P_ContentItem_Libraries.Add(this);
						this._ContentItemId = value.Id;
					}
					else
					{
						this._ContentItemId = default(int);
					}
					this.SendPropertyChanged("H5P_ContentItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_ContentItem_Library", Storage="_H5P_Library", ThisKey="LibraryId", OtherKey="Id", IsForeignKey=true)]
		public H5P_Library H5P_Library
		{
			get
			{
				return this._H5P_Library.Entity;
			}
			set
			{
				H5P_Library previousValue = this._H5P_Library.Entity;
				if (((previousValue != value) 
							|| (this._H5P_Library.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._H5P_Library.Entity = null;
						previousValue.H5P_ContentItem_Libraries.Remove(this);
					}
					this._H5P_Library.Entity = value;
					if ((value != null))
					{
						value.H5P_ContentItem_Libraries.Add(this);
						this._LibraryId = value.Id;
					}
					else
					{
						this._LibraryId = default(int);
					}
					this.SendPropertyChanged("H5P_Library");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[H5P.ContentItem.EmbedTypes]")]
	public partial class H5P_ContentItem_EmbedType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ContentId;
		
		private string _Value;
		
		private EntityRef<H5P_ContentItem> _H5P_ContentItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnContentIdChanging(int value);
    partial void OnContentIdChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public H5P_ContentItem_EmbedType()
		{
			this._H5P_ContentItem = default(EntityRef<H5P_ContentItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentId", DbType="Int NOT NULL")]
		public int ContentId
		{
			get
			{
				return this._ContentId;
			}
			set
			{
				if ((this._ContentId != value))
				{
					if (this._H5P_ContentItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnContentIdChanging(value);
					this.SendPropertyChanging();
					this._ContentId = value;
					this.SendPropertyChanged("ContentId");
					this.OnContentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_ContentItem_H5P_ContentItem_EmbedType", Storage="_H5P_ContentItem", ThisKey="ContentId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public H5P_ContentItem H5P_ContentItem
		{
			get
			{
				return this._H5P_ContentItem.Entity;
			}
			set
			{
				H5P_ContentItem previousValue = this._H5P_ContentItem.Entity;
				if (((previousValue != value) 
							|| (this._H5P_ContentItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._H5P_ContentItem.Entity = null;
						previousValue.H5P_ContentItem_EmbedTypes.Remove(this);
					}
					this._H5P_ContentItem.Entity = value;
					if ((value != null))
					{
						value.H5P_ContentItem_EmbedTypes.Add(this);
						this._ContentId = value.Id;
					}
					else
					{
						this._ContentId = default(int);
					}
					this.SendPropertyChanged("H5P_ContentItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[H5P.Libraries]")]
	public partial class H5P_Library : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Title;
		
		private string _MachineName;
		
		private int _MajorVersion;
		
		private int _MinorVersion;
		
		private int _PatchVersion;
		
		private System.Nullable<int> _CoreApiMajorVersion;
		
		private System.Nullable<int> _CoreApiMinorVersion;
		
		private string _Author;
		
		private System.DateTime _AddedOn;
		
		private System.DateTime _UpdatedOn;
		
		private EntitySet<H5P_ContentItem_Library> _H5P_ContentItem_Libraries;
		
		private EntitySet<H5P_Library_File> _H5P_Library_Files;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnMachineNameChanging(string value);
    partial void OnMachineNameChanged();
    partial void OnMajorVersionChanging(int value);
    partial void OnMajorVersionChanged();
    partial void OnMinorVersionChanging(int value);
    partial void OnMinorVersionChanged();
    partial void OnPatchVersionChanging(int value);
    partial void OnPatchVersionChanged();
    partial void OnCoreApiMajorVersionChanging(System.Nullable<int> value);
    partial void OnCoreApiMajorVersionChanged();
    partial void OnCoreApiMinorVersionChanging(System.Nullable<int> value);
    partial void OnCoreApiMinorVersionChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnAddedOnChanging(System.DateTime value);
    partial void OnAddedOnChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public H5P_Library()
		{
			this._H5P_ContentItem_Libraries = new EntitySet<H5P_ContentItem_Library>(new Action<H5P_ContentItem_Library>(this.attach_H5P_ContentItem_Libraries), new Action<H5P_ContentItem_Library>(this.detach_H5P_ContentItem_Libraries));
			this._H5P_Library_Files = new EntitySet<H5P_Library_File>(new Action<H5P_Library_File>(this.attach_H5P_Library_Files), new Action<H5P_Library_File>(this.detach_H5P_Library_Files));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this.OnMachineNameChanging(value);
					this.SendPropertyChanging();
					this._MachineName = value;
					this.SendPropertyChanged("MachineName");
					this.OnMachineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MajorVersion", DbType="Int NOT NULL")]
		public int MajorVersion
		{
			get
			{
				return this._MajorVersion;
			}
			set
			{
				if ((this._MajorVersion != value))
				{
					this.OnMajorVersionChanging(value);
					this.SendPropertyChanging();
					this._MajorVersion = value;
					this.SendPropertyChanged("MajorVersion");
					this.OnMajorVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinorVersion", DbType="Int NOT NULL")]
		public int MinorVersion
		{
			get
			{
				return this._MinorVersion;
			}
			set
			{
				if ((this._MinorVersion != value))
				{
					this.OnMinorVersionChanging(value);
					this.SendPropertyChanging();
					this._MinorVersion = value;
					this.SendPropertyChanged("MinorVersion");
					this.OnMinorVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatchVersion", DbType="Int NOT NULL")]
		public int PatchVersion
		{
			get
			{
				return this._PatchVersion;
			}
			set
			{
				if ((this._PatchVersion != value))
				{
					this.OnPatchVersionChanging(value);
					this.SendPropertyChanging();
					this._PatchVersion = value;
					this.SendPropertyChanged("PatchVersion");
					this.OnPatchVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreApiMajorVersion", DbType="Int")]
		public System.Nullable<int> CoreApiMajorVersion
		{
			get
			{
				return this._CoreApiMajorVersion;
			}
			set
			{
				if ((this._CoreApiMajorVersion != value))
				{
					this.OnCoreApiMajorVersionChanging(value);
					this.SendPropertyChanging();
					this._CoreApiMajorVersion = value;
					this.SendPropertyChanged("CoreApiMajorVersion");
					this.OnCoreApiMajorVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreApiMinorVersion", DbType="Int")]
		public System.Nullable<int> CoreApiMinorVersion
		{
			get
			{
				return this._CoreApiMinorVersion;
			}
			set
			{
				if ((this._CoreApiMinorVersion != value))
				{
					this.OnCoreApiMinorVersionChanging(value);
					this.SendPropertyChanging();
					this._CoreApiMinorVersion = value;
					this.SendPropertyChanged("CoreApiMinorVersion");
					this.OnCoreApiMinorVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime NOT NULL")]
		public System.DateTime AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this.OnAddedOnChanging(value);
					this.SendPropertyChanging();
					this._AddedOn = value;
					this.SendPropertyChanged("AddedOn");
					this.OnAddedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_ContentItem_Library", Storage="_H5P_ContentItem_Libraries", ThisKey="Id", OtherKey="LibraryId")]
		public EntitySet<H5P_ContentItem_Library> H5P_ContentItem_Libraries
		{
			get
			{
				return this._H5P_ContentItem_Libraries;
			}
			set
			{
				this._H5P_ContentItem_Libraries.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_Library_File", Storage="_H5P_Library_Files", ThisKey="Id", OtherKey="LibraryId")]
		public EntitySet<H5P_Library_File> H5P_Library_Files
		{
			get
			{
				return this._H5P_Library_Files;
			}
			set
			{
				this._H5P_Library_Files.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_H5P_ContentItem_Libraries(H5P_ContentItem_Library entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library = this;
		}
		
		private void detach_H5P_ContentItem_Libraries(H5P_ContentItem_Library entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library = null;
		}
		
		private void attach_H5P_Library_Files(H5P_Library_File entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library = this;
		}
		
		private void detach_H5P_Library_Files(H5P_Library_File entity)
		{
			this.SendPropertyChanging();
			entity.H5P_Library = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[H5P.Library.Files]")]
	public partial class H5P_Library_File : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _LibraryId;
		
		private int _Type;
		
		private string _Path;
		
		private int _Order;
		
		private EntityRef<H5P_Library> _H5P_Library;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLibraryIdChanging(int value);
    partial void OnLibraryIdChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    partial void OnOrderChanging(int value);
    partial void OnOrderChanged();
    #endregion
		
		public H5P_Library_File()
		{
			this._H5P_Library = default(EntityRef<H5P_Library>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibraryId", DbType="Int NOT NULL")]
		public int LibraryId
		{
			get
			{
				return this._LibraryId;
			}
			set
			{
				if ((this._LibraryId != value))
				{
					if (this._H5P_Library.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLibraryIdChanging(value);
					this.SendPropertyChanging();
					this._LibraryId = value;
					this.SendPropertyChanged("LibraryId");
					this.OnLibraryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this.OnPathChanging(value);
					this.SendPropertyChanging();
					this._Path = value;
					this.SendPropertyChanged("Path");
					this.OnPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int NOT NULL")]
		public int Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this.OnOrderChanging(value);
					this.SendPropertyChanging();
					this._Order = value;
					this.SendPropertyChanged("Order");
					this.OnOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="H5P_Library_H5P_Library_File", Storage="_H5P_Library", ThisKey="LibraryId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public H5P_Library H5P_Library
		{
			get
			{
				return this._H5P_Library.Entity;
			}
			set
			{
				H5P_Library previousValue = this._H5P_Library.Entity;
				if (((previousValue != value) 
							|| (this._H5P_Library.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._H5P_Library.Entity = null;
						previousValue.H5P_Library_Files.Remove(this);
					}
					this._H5P_Library.Entity = value;
					if ((value != null))
					{
						value.H5P_Library_Files.Add(this);
						this._LibraryId = value.Id;
					}
					else
					{
						this._LibraryId = default(int);
					}
					this.SendPropertyChanged("H5P_Library");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
